Feat: add Windows Structure Exceptions Suppot with minimize modification (#94)
* Feat: add Windows Structure Exceptions Suppot with minimize modification
        *apart builtin and signal header files to different dirs
        according to different OS C/C++ Library
        *use VEH(Vector Exception Handing) to register exception
         handler and add exception nums which is mapping
         to linux signal(may not accurate,stil need further test)
        *replace begin_catch_exception() with
        begin_catch_exception_wrapper() to smooth the gap between diff
        CAPI
        *add copy-assgin operator function in struct exception_record_t
        otherwise it will raise MSVC error C2280
        (function "exception_record t::operator=(const exception_record t &)" (declared implicitly) cannot be referenced -- it is a deleted function)
        because MSVC would surpress default copy-assign operator func
	*add comment for ABI/API indepdent header files
	*standardized naming for begin/end_catch_exception

* Update signal.hpp

* Remove identical code

* Update builtin.hpp

---------

Co-authored-by: Wei Song (宋威) <wsong83@gmail.com>